transformation_showcase:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: dev_database.duckdb
      threads: 4
      
    staging:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      dbname: staging
      schema: analytics
      threads: 8
      
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: TRANSFORMER
      database: PRODUCTION
      warehouse: TRANSFORMING
      schema: ANALYTICS
      threads: 16
      query_tag: dbt_transformation